// Mocks generated by Mockito 5.0.7 from annotations
// in users_client/test/orion_users_cli_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:users_client/client/user_ws.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [UsersWebService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersWebService extends _i1.Mock implements _i2.UsersWebService {
  MockUsersWebService() {
    _i1.throwOnMissingStub(this);
  }
}
