name: users_client
description: Orion Users service Client.
version: 0.1.8
homepage: https://github.com/orion-services/users_client

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  prompts: ^2.0.0
  http: ^0.13.4
  web_socket_channel: ^2.2.0
  mockito: ^5.0.7
  email_validator: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  pedantic: ^1.8.0
  test: ^1.6.0
