name: users_client
description: Orion Users Client
version: 1.0.0
homepage: https://github.com/orion-services/users_client

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  prompts: ^1.3.1
  http: ^0.12.1
  web_socket_channel: ^1.1.0
  mockito: ^5.0.7
  email_validator: ^2.0.1

dev_dependencies:
  build_runner: ^1.9.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
